/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package qlearning;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.border.Border;

/**
 *
 * @author Grupo 6
 */
public class Tablero extends JFrame implements ActionListener {

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        spinEps.setModel(new SpinnerNumberModel(0.1, 0.0, 1.0, 0.05));
        textBueno.setText(String.valueOf(ConfTab.getrBueno()));
        textMalo.setText(String.valueOf(ConfTab.getrMalo()));
        textExc.setText(String.valueOf(ConfTab.getrExc()));
        textPozo.setText(String.valueOf(ConfTab.getrPozo()));
        textFinal.setText(String.valueOf(ConfTab.getrFin()));
        textNeutro.setText(String.valueOf(ConfTab.getrNeutro()));
        textEp.setText(String.valueOf(ConfTab.getEpisodios()));
        textGamma.setText(String.valueOf(ConfTab.getGamma()));
        textEpCorte.setText(String.valueOf(ConfTab.getEpisodios()));
        panGral.setLayout(new BorderLayout());
        panGral.add(panBot, BorderLayout.WEST);
        panGral.add(panCentro, BorderLayout.CENTER);
        panGral.add(panSur, BorderLayout.NORTH);
        panGral.add(panConsola, BorderLayout.SOUTH);
        panGral.add(panDer, BorderLayout.EAST);
    }
    
    public static String letra = null;
    public static Color fondo = new Color (255, 215, 0);
    public static Color colMalo = new Color(205, 0, 0);
    public static Color colBueno = new Color(0, 154, 205);
    public static Color colExc = new Color(0, 205, 0);
    public static Color colPozo = new Color(0, 0, 0);
    public static Color colNeutro = new Color (200, 200, 200);
    public static Color colInFin = new Color (255, 215, 0);
    public static JButton[] estados;
    public static int posFinal;
    public static int posInic = 0;
    public static int episodio = 0;
    public static JTextField epiHechos;
    public Matriz m;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jFrame1 = new javax.swing.JFrame();
        panGral = new javax.swing.JPanel();
        panBot = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        comboSize = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox();
        radioEpsilon = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        spinEps = new javax.swing.JSpinner();
        radioSoft = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        textTau = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        comboMapa = new javax.swing.JComboBox();
        comboTableros = new javax.swing.JComboBox();
        btnGuardar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        textEpCorte = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnMostrarQ = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        btnFinal = new javax.swing.JButton();
        panCentro = new javax.swing.JPanel();
        panSur = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textMalo = new javax.swing.JTextField();
        textBueno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textExc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textFinal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        textPozo = new javax.swing.JTextField();
        textNeutro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        textEp = new javax.swing.JTextField();
        textGamma = new javax.swing.JTextField();
        panDer = new javax.swing.JPanel();
        panConsola = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        panAvance = new javax.swing.JPanel();
        btnAprende = new javax.swing.JButton();
        btnRecorrer = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        panProgreso = new javax.swing.JPanel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Q-learning");
        setBounds(new java.awt.Rectangle(0, 0, 800, 500));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 800));

        jLabel6.setText("Tamaño");

        comboSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6x6", "7x7", "8x8", "9x9", "10x10" }));
        comboSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSizeActionPerformed(evt);
            }
        });

        jLabel5.setText("Tableros predefinidos");

        jLabel1.setText("Tipo de Estado");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inicial", "Final", "Malo", "Bueno", "Excelente", "Neutro", "Pozo" }));
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioEpsilon);
        radioEpsilon.setText("e-greedy");
        radioEpsilon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEpsilonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("є");

        spinEps.setEnabled(false);
        spinEps.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spinEpsFocusGained(evt);
            }
        });

        buttonGroup1.add(radioSoft);
        radioSoft.setText("Softmax");
        radioSoft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSoftActionPerformed(evt);
            }
        });

        jLabel3.setText("Tau");

        textTau.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        textTau.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textTauFocusGained(evt);
            }
        });

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboMapa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todo Neutro", "Todo Excelente", "Columnas", "Aleatorio" }));
        comboMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMapaActionPerformed(evt);
            }
        });

        comboTableros.setEnabled(false);
        comboTableros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTablerosActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar Tablero");
        btnGuardar.setToolTipText("");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel7.setText("Cargar Tablero");

        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selección de Política", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel2.setText("Intervalo de corte");

        jSeparator3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Comparación de Matriz Q", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnMostrarQ.setText("Ver Q");
        btnMostrarQ.setEnabled(false);
        btnMostrarQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarQActionPerformed(evt);
            }
        });

        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        btnFinal.setText("Ir al Final");
        btnFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panBotLayout = new javax.swing.GroupLayout(panBot);
        panBot.setLayout(panBotLayout);
        panBotLayout.setHorizontalGroup(
            panBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(panBotLayout.createSequentialGroup()
                .addComponent(jSeparator3)
                .addGap(5, 5, 5))
            .addGroup(panBotLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBotLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(25, 25, 25)
                        .addComponent(textEpCorte)
                        .addContainerGap())
                    .addGroup(panBotLayout.createSequentialGroup()
                        .addComponent(btnMostrarQ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnContinuar))
                    .addGroup(panBotLayout.createSequentialGroup()
                        .addGroup(panBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panBotLayout.createSequentialGroup()
                                .addGroup(panBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panBotLayout.createSequentialGroup()
                                        .addComponent(radioEpsilon)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4))
                                    .addGroup(panBotLayout.createSequentialGroup()
                                        .addComponent(radioSoft)
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel3)))
                                .addGap(18, 18, 18)
                                .addGroup(panBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spinEps, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(textTau)))
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(comboSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(panBotLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(33, 33, 33)
                                .addComponent(comboTableros, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panBotLayout.createSequentialGroup()
                                .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)))
                        .addGap(5, 5, 5))))
            .addGroup(panBotLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnFinal)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panBotLayout.setVerticalGroup(
            panBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBotLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addGap(9, 9, 9)
                .addGroup(panBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboTableros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(panBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioEpsilon)
                    .addComponent(jLabel4)
                    .addComponent(spinEps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioSoft)
                    .addComponent(jLabel3)
                    .addComponent(textTau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textEpCorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnContinuar)
                    .addComponent(btnMostrarQ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinal)
                .addContainerGap())
        );

        panCentro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panCentro.setMaximumSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout panCentroLayout = new javax.swing.GroupLayout(panCentro);
        panCentro.setLayout(panCentroLayout);
        panCentroLayout.setHorizontalGroup(
            panCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
        );
        panCentroLayout.setVerticalGroup(
            panCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );

        jLabel8.setText("Configuraciones");

        jLabel9.setText("Malo");

        jLabel10.setText("Bueno");

        textMalo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textMaloFocusLost(evt);
            }
        });

        textBueno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textBuenoFocusLost(evt);
            }
        });

        jLabel11.setText("Excelente");

        textExc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textExcFocusLost(evt);
            }
        });

        jLabel12.setText("Final");

        textFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFinalFocusLost(evt);
            }
        });

        jLabel13.setText("Pozo");

        jLabel14.setText("Neutro");

        textPozo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textPozoFocusLost(evt);
            }
        });

        textNeutro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textNeutroFocusLost(evt);
            }
        });

        jLabel15.setText("Nro Episodios");

        jLabel16.setText("Gamma");

        textEp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textEpFocusLost(evt);
            }
        });

        textGamma.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textGammaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout panSurLayout = new javax.swing.GroupLayout(panSur);
        panSur.setLayout(panSurLayout);
        panSurLayout.setHorizontalGroup(
            panSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSurLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(panSurLayout.createSequentialGroup()
                        .addGroup(panSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textBueno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textMalo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panSurLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(textExc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSurLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(34, 34, 34)
                                .addComponent(textFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panSurLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textPozo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panSurLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(textNeutro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panSurLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textGamma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panSurLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(textEp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panSurLayout.setVerticalGroup(
            panSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSurLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(panSurLayout.createSequentialGroup()
                        .addGroup(panSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(textExc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(textPozo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(textEp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(textFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(textNeutro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(textGamma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textBueno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(textMalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panDerLayout = new javax.swing.GroupLayout(panDer);
        panDer.setLayout(panDerLayout);
        panDerLayout.setHorizontalGroup(
            panDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panDerLayout.setVerticalGroup(
            panDerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        btnAprende.setText("Aprender");
        btnAprende.setToolTipText("");
        btnAprende.setEnabled(false);
        btnAprende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprendeActionPerformed(evt);
            }
        });

        btnRecorrer.setText("Recorrer");
        btnRecorrer.setEnabled(false);
        btnRecorrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecorrerActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panProgresoLayout = new javax.swing.GroupLayout(panProgreso);
        panProgreso.setLayout(panProgresoLayout);
        panProgresoLayout.setHorizontalGroup(
            panProgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );
        panProgresoLayout.setVerticalGroup(
            panProgresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panAvanceLayout = new javax.swing.GroupLayout(panAvance);
        panAvance.setLayout(panAvanceLayout);
        panAvanceLayout.setHorizontalGroup(
            panAvanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAvanceLayout.createSequentialGroup()
                .addGroup(panAvanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAvanceLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panAvanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panAvanceLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(panProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panAvanceLayout.createSequentialGroup()
                                .addComponent(btnAprende)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRecorrer))))
                    .addGroup(panAvanceLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        panAvanceLayout.setVerticalGroup(
            panAvanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAvanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panAvanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAprende)
                    .addComponent(btnRecorrer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout panConsolaLayout = new javax.swing.GroupLayout(panConsola);
        panConsola.setLayout(panConsolaLayout);
        panConsolaLayout.setHorizontalGroup(
            panConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsolaLayout.createSequentialGroup()
                .addComponent(panAvance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        panConsolaLayout.setVerticalGroup(
            panConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConsolaLayout.createSequentialGroup()
                .addGroup(panConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panConsolaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panAvance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panGralLayout = new javax.swing.GroupLayout(panGral);
        panGral.setLayout(panGralLayout);
        panGralLayout.setHorizontalGroup(
            panGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panGralLayout.createSequentialGroup()
                        .addComponent(panBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(panGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panSur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(371, 371, 371)
                .addComponent(panDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panGralLayout.setVerticalGroup(
            panGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGralLayout.createSequentialGroup()
                .addGroup(panGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panDer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panGralLayout.createSequentialGroup()
                        .addGroup(panGralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panGralLayout.createSequentialGroup()
                                .addComponent(panSur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(panGralLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(panConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)))
                .addGap(23, 23, 23))
        );

        panCentro.getAccessibleContext().setAccessibleName("");
        panCentro.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panGral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panGral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 759, 600);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnAprendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprendeActionPerformed
        
        ConfTab.corteEpisodios = Integer.valueOf(textEpCorte.getText());
        politicaElegida();
        m = new Matriz();
        m.inicializarEstados();
        btnMostrarQ.setEnabled(true);
        finalUnico();
        matrizR();
        
    }//GEN-LAST:event_btnAprendeActionPerformed

    private void radioSoftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSoftActionPerformed

        textTau.setEnabled(true);
        textTau.requestFocusInWindow();
        spinEps.setEnabled(false);
    }//GEN-LAST:event_radioSoftActionPerformed

    private void radioEpsilonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEpsilonActionPerformed

        spinEps.setEnabled(true);
        spinEps.requestFocusInWindow();
        textTau.setValue(0);
        textTau.setEnabled(false);
    }//GEN-LAST:event_radioEpsilonActionPerformed

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        tipoDePantalla();
    }//GEN-LAST:event_comboTipoActionPerformed

    private void comboSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSizeActionPerformed
        iniciar();
        comboMapa.setEnabled(true);
    }//GEN-LAST:event_comboSizeActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Estadistica.guardarTablero();
        cantTableros();
        comboTableros.setEnabled(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void comboTablerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTablerosActionPerformed
        redibujar();
        int a = (int) Math.sqrt(estados.length);
        ConfTab.setSize(a);
    }//GEN-LAST:event_comboTablerosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiarTablero();
        btnAprende.setEnabled(false);
        btnRecorrer.setEnabled(false);
        radioEpsilon.setSelected(false);
        radioSoft.setSelected(false);
        textTau.setValue(0);
        textTau.setEnabled(false);
        spinEps.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void spinEpsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spinEpsFocusGained
        btnAprende.setEnabled(true);
    }//GEN-LAST:event_spinEpsFocusGained

    private void textTauFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textTauFocusGained
        btnAprende.setEnabled(true);
    }//GEN-LAST:event_textTauFocusGained

    private void textMaloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textMaloFocusLost
        ConfTab.setrMalo(Float.parseFloat(textMalo.getText()));
    }//GEN-LAST:event_textMaloFocusLost

    private void textBuenoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textBuenoFocusLost
        ConfTab.setrBueno(Float.parseFloat(textBueno.getText()));
    }//GEN-LAST:event_textBuenoFocusLost

    private void textExcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textExcFocusLost
        ConfTab.setrExc(Float.parseFloat(textExc.getText()));
    }//GEN-LAST:event_textExcFocusLost

    private void textFinalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFinalFocusLost
        ConfTab.setrFin(Float.parseFloat(textFinal.getText()));
    }//GEN-LAST:event_textFinalFocusLost

    private void textPozoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPozoFocusLost
        ConfTab.setrPozo(Float.parseFloat(textPozo.getText()));
    }//GEN-LAST:event_textPozoFocusLost

    private void textNeutroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNeutroFocusLost
        ConfTab.setrNeutro(Float.parseFloat(textNeutro.getText()));
    }//GEN-LAST:event_textNeutroFocusLost

    private void textEpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textEpFocusLost
        ConfTab.setEpisodios(Integer.parseInt(textEp.getText()));
    }//GEN-LAST:event_textEpFocusLost

    private void textGammaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textGammaFocusLost
        ConfTab.setGamma(Float.parseFloat(textGamma.getText()));
    }//GEN-LAST:event_textGammaFocusLost

    private void comboMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMapaActionPerformed
        mapaPantalla();
    }//GEN-LAST:event_comboMapaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRecorrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecorrerActionPerformed
        ubicarInicio();
        mostrarRecorrido();
    }//GEN-LAST:event_btnRecorrerActionPerformed

    private void btnFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalActionPerformed
       ConfTab.corteEpisodios = ConfTab.getEpisodios();
       m.aprendizaje.resume();
    }//GEN-LAST:event_btnFinalActionPerformed

    private void btnMostrarQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarQActionPerformed
        MatrizQ m = new MatrizQ();
        m.setVisible(true);
    }//GEN-LAST:event_btnMostrarQActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
       m.aprendizaje.resume();
    }//GEN-LAST:event_btnContinuarActionPerformed

    // <editor-fold defaultstate="collapsed" desc="sizeDePantalla () Toma el valor de tamaño del tablero desde el comboBox">
    private void sizeDePantalla (){
        int size= 0;
        String aux = (String)comboSize.getSelectedItem();
        switch(aux){
            case "6x6":size= 6;
                break;
            case "7x7":size= 7;
                break;
            case "8x8":size= 8;
                break;
            case "9x9":size= 9;
                break;
            case "10x10":size=10;
                break;
        }    
        ConfTab.setSize(size);
    }
    //</editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="mapaPantalla() Genera el tipo de tablero seleccionado">
    public void mapaPantalla(){
        String aux = (String) comboMapa.getSelectedItem();
        switch(aux){
            case "Todo Neutro":iniciar();
                break;
            case "Todo Excelente":todoExc(ConfTab.getSize());
                break;
            case "Columnas":enColumnas(ConfTab.getSize());
                break;
            case "Aleatorio":aleatorio(ConfTab.getSize());
                break;
        }
    }
    //</editor-fold>
    
    //<editor-fold defaultstate="collapsed" desc="tipoDePantalla() Toma el valor de que tipo de estado se quiere colocar en el tablero">
    public String tipoDePantalla(){
        String aux = (String) comboTipo.getSelectedItem();
        switch(aux){
            case "Malo":{
                letra = "M";
                fondo = colMalo;
            }
                break;
            case "Bueno":{
                letra = "B";
                fondo = colBueno;
            }
                break;
            case "Excelente":{
                letra = "E";
                fondo = colExc;
            }
                break;
            case "Neutro":{
                letra = "";
                fondo = colNeutro;
            }
                break;
            case "Pozo":{
                letra = "P";
                fondo = colPozo;
            }
                break;
            case "Inicial":{
                letra = "Inicial";
                fondo = colInFin;
            }
                break;
            case "Final":{
                letra = "Final";
                fondo = colInFin;
            }
                break;
        }
        return aux;
    }
    //</editor-fold>
    
    //Dependiendo de que politica se selecciona actualiza el valor de epsilon o tau en la clase ConfTab
    public void politicaElegida(){
         if(radioEpsilon.isSelected()){
             ConfTab.setEpsilon((double) spinEps.getValue());
             //ConfTab.setEpsilon(Float.parseFloat(textEpsilon.getText()));
         }
         else{
             ConfTab.setTau(Double.parseDouble(textTau.getText()) );
             //ConfTab.setTau(Float.parseFloat(textTau.getText()));
         }
    }
    
    //Pinta un tablero con el tama�o elegido y todos los estados neutro
    public void iniciar(){
        sizeDePantalla();
        int size = ConfTab.size;
        estados = new JButton[size*size];
        panCentro.setVisible(false);
        panCentro.removeAll();
        panCentro.setLayout(new GridLayout(size, size));
        for (int i = 0; i < (size*size); i++) {
                            
            final JButton temp = new JButton();
            temp.setBackground(colNeutro);
            temp.setSize(290/size, 290/size);
            temp.setForeground(Color.WHITE);
            temp.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {                       
                    if ("Final".equals(tipoDePantalla())){
                        if (!finalUnico()){
                            estados[posFinal].setBackground(colNeutro);
                            estados[posFinal].setText("");
                            panCentro.remove(posFinal);
                            panCentro.add(estados[posFinal], posFinal);
                            
                        }
                    }
                    if ("Inicial".equals(tipoDePantalla())){
                        btnRecorrer.setEnabled(true);
                        if (!inicialUnico()){
                            estados[posInic].setBackground(colNeutro);
                            estados[posInic].setText("");
                            panCentro.remove(posInic);
                            panCentro.add(estados[posInic], posInic);
                        }
                    }
                    temp.setText(letra);
                    temp.setBackground(fondo);
                    textArea.setText("");
                }
            });

            //agregar el boton al panel
            panCentro.add(temp);
            //agregar el boton al arreglo
            estados[i] = temp;
        }
        panCentro.setVisible(true);

        
    }
    
    //Pinta un tablero definiendo los tipos de estado aleatoriamente
    public void aleatorio(int size){

        panCentro.setLayout(new GridLayout(size, size));
        for (int i = 0; i < size*size; i++) {
            float x = new Random().nextFloat();
            if (x < 0.2) {
                estados[i].setText("M");
                estados[i].setBackground(colMalo);
            } else {
                if (x < 0.5) {
                    estados[i].setText("B");
                    estados[i].setBackground(colBueno);
                } else {
                    if (x < 0.6) {
                        estados[i].setText("E");
                        estados[i].setBackground(colExc);
                    } else {
                        if (x < 0.7) {
                            estados[i].setText("P");
                            estados[i].setBackground(colPozo);
                        }
                        else {
                            estados[i].setText("");
                            estados[i].setBackground(colNeutro);
                        }
                    }
                }
            }
            panCentro.add(estados[i]);
        }
               
        colocarFinal(size);
        panGral.repaint();
        jFrame1.pack();
    }  
    
    //Coloca el estado final en una posicion aleatoria del tablero
    public void colocarFinal(int size){
        //Para colocar el estado final en una posicion aleatoria
        int y = new Random().nextInt(size*size);
        estados[y].setText("Final");
        estados[y].setBackground(colInFin);
        estados[y].setForeground(Color.BLACK);
        posFinal = y;
        panCentro.remove(y);
        panCentro.add(estados[y], y);
    }
    
    public void todoExc(int size) {
        
        panCentro.setLayout(new GridLayout(size, size));
        for (int i = 0; i < size*size; i++) {
            estados[i].setText("E");
            estados[i].setBackground(colExc);
            panCentro.add(estados[i]);
        }
    }
    
    public void enColumnas(int size){
        int aux;
        for (int i = 0; i < size; i++) {
            switch(i){
                case 0: case 5:{
                    fondo = colExc;
                    letra = "E";
                }
                    break;
                case 1: case 6:{
                    fondo = colBueno;
                    letra = "B";
                }
                    break;
                case 2: case 7:{
                    fondo = colMalo;
                    letra = "M";

                }
                    break;
                case 3: case 8:{
                    fondo = colPozo;
                    letra = "P";
                }
                    break;
                case 4: case 9:{
                    fondo = colNeutro;
                    letra = "";

                }    
            }
            for (int j = 0; j < size; j++) {
                aux = i + (size * j);
                estados[aux].setBackground(fondo);
                estados[aux].setText(letra);
                panCentro.add(estados[aux], aux);
            }
            if ( (i == 3) | (i == 8) ) {
                Random x;
                x = new Random();
                int aleat = x.nextInt(size);
                aux = i + (size * aleat);
                estados[aux].setBackground(colNeutro);
                estados[aux].setText("");
                panCentro.add(estados[aux], aux);
            }
        }
    }
    
    public void redibujar(){
        JButton[] tablero = Estadistica.cargarTablero(comboTableros.getSelectedIndex());
        int x = (int) Math.sqrt(tablero.length);
        panCentro.removeAll();
        panCentro.setLayout(new GridLayout(x, x));
        estados = new JButton[tablero.length];
        for (int i = 0; i < tablero.length; i++) {
            tablero[i].setBorder(BorderFactory.createLineBorder(new Color (130, 130, 130), 1));
            estados[i] = tablero[i];
            panCentro.add(tablero[i]);
        }
        panCentro.repaint();
        jFrame1.pack();
        panCentro.setVisible(true);
        
    }
    
    //Segun los tipos de estado, actualiza los valores de recompensa en el arreglo de estados de Matriz
    public void matrizR(){
        int size = ConfTab.getSize();
        for (int i = 0; i < (size*size); i++) {
            if (estados[i].getBackground() == colMalo){
                Matriz.estados[i].setRecompensa(ConfTab.getrMalo());
            } else {
                if (estados[i].getBackground() == colBueno){
                    Matriz.estados[i].setRecompensa(ConfTab.getrBueno());
                } else {
                    if (estados[i].getBackground() == colExc){
                        Matriz.estados[i].setRecompensa(ConfTab.getrExc());
                    } else {
                        if (estados[i].getBackground() == colPozo) {
                            Matriz.estados[i].setRecompensa(ConfTab.getrPozo());
                        } else {
                            if ("Final".equals(estados[i].getText())){
                                Matriz.estados[i].setRecompensa(ConfTab.getrFin());
                                Matriz.actualizarEstadoFinal(i);
                                posFinal = i;
                            } else
                                Matriz.estados[i].setRecompensa(ConfTab.getrNeutro());
                        }
                    }
                }
            }
        }
    }
    
    public void limpiarTablero(){
        
        int x = estados.length;
        for (int i = 0; i < x; i++) {
            estados[i].removeAll();
        }
        iniciar();
        textArea.setText("");
    }
    
    //Verifica que el final sea unico
    public Boolean finalUnico(){
        Boolean flag = true;
        for (int i = 0; i < (ConfTab.getSize()*ConfTab.getSize()); i++) {
            if ("Final".equals(estados[i].getText())){
                flag = false;
                posFinal = i;
            }
        }
        return flag;
    }
    
    //Verifica que el inicio sea unico
    public Boolean inicialUnico(){
        Boolean flag = true;
        for (int i = 0; i < (ConfTab.getSize()*ConfTab.getSize()); i++) {
            if ("Inicial".equals(estados[i].getText())){
                flag = false;
                posInic = i;
            }
        }
        return flag;
    }
    
    public void ubicarInicio(){
        for (int i = 0; i < (ConfTab.size*ConfTab.size); i++) {
            if("Inicial".equals(estados[i].getText()))
                posInic = i;
        }
    }
    
    //Pinta el recorrido aprendido
    public void mostrarRecorrido(){
        Border linea = BorderFactory.createLineBorder(colInFin, 5);
        ArrayList elCamino;
        elCamino = Matriz.recorrer();
        float total = 0;
        if (elCamino.isEmpty())
            JOptionPane.showMessageDialog(jFrame1, "No es posible llegar al final", "Estado inalcanzable", JOptionPane.ERROR_MESSAGE);
        for (int i = 0; i < (elCamino.size()); i++) {
            estados[(int)elCamino.get(i)].setText("E "+elCamino.get(i));
            estados[(int)elCamino.get(i)].setBorder(linea);
            textArea.append("Estado visitado:" + String.valueOf(elCamino.get(i))+" Q = "+String.valueOf(elCamino.get(i+1))+"\n" );
            total += (float) elCamino.get(i+1);
            panCentro.remove((int) elCamino.get(i));
            panCentro.add(estados[(int)elCamino.get(i)], (int)elCamino.get(i));
            i+=1; 
        }
        textArea.append("Q acumulado = "+total);
    }
    
    public void cantTableros(){
        int longTab = Estadistica.tableros.size();
        comboTableros.insertItemAt(longTab, longTab-1);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAprende;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnFinal;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrarQ;
    private javax.swing.JButton btnRecorrer;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox comboMapa;
    private javax.swing.JComboBox comboSize;
    private javax.swing.JComboBox comboTableros;
    private javax.swing.JComboBox comboTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel panAvance;
    private javax.swing.JPanel panBot;
    private javax.swing.JPanel panCentro;
    private javax.swing.JPanel panConsola;
    private javax.swing.JPanel panDer;
    private javax.swing.JPanel panGral;
    private javax.swing.JPanel panProgreso;
    private javax.swing.JPanel panSur;
    private javax.swing.JRadioButton radioEpsilon;
    private javax.swing.JRadioButton radioSoft;
    private javax.swing.JSpinner spinEps;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField textBueno;
    private javax.swing.JTextField textEp;
    private javax.swing.JTextField textEpCorte;
    private javax.swing.JTextField textExc;
    private javax.swing.JTextField textFinal;
    private javax.swing.JTextField textGamma;
    private javax.swing.JTextField textMalo;
    private javax.swing.JTextField textNeutro;
    private javax.swing.JTextField textPozo;
    private javax.swing.JFormattedTextField textTau;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
